version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql

    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
        - mysql
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - laravel

  redis:
    image: redis:5
    container_name: redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - laravel

  node:
    image: node:12
    container_name: node
    user: node
    working_dir: /assets
    command: npm run dev
    volumes:
      - ./:/assets
    networks:
      - laravel

volumes:
  mysqldata:
  redisdata:

networks:
  laravel:
    driver: bridge
